config/routes.rb
Rails.application.routes.draw do










 as :user do
   get 'registrations/:id/edit' => 'registrations#edit', :as => :edit_user_profile
 end






  devise_for :users,
           :controllers  => {
             :registrations => 'registrations',

           }



  # get 'admins/:id/edit' => 'admins#edit', :as => :edit_admin


  root 'events#index'

  get 'admin/index' => 'admin#index'
  get 'admin/dashboard' => 'admin#dashboard'

  # get 'events/list' => 'events#list'

  get 'events/admin' => 'events#admin'

  get 'eats/admin' => 'eats#admin'
  get 'eats/index' => 'eats#index'

  get 'covers/index' => 'covers#index'

  get 'menus/:id/edit' => 'menus#edit'


  get 'curries/admin' => 'curries#admin'

  resources :events

  resources :eats

  resources :covers

  resources :curries

  resources :admin

  resources :menus

  resources :opening_hours









end

app/models/curry.rb
class Curry < ActiveRecord::Base
end

app/controllers/curries_controller.rb
class CurriesController < ApplicationController

layout "devise", only: [:admin, :new, :create, :show, :edit, :update, :destroy]

  before_action :find_curry, only: [:show, :edit, :update, :destroy]


  def index
    @curries = Curry.all
  end

  def admin
     @curries = Curry.all
  end

  def edit
  end

  # def new
  #     @curry = Curry.new
  # end

  # def create
  #   @curry = Curry.new(curry_params)
  #   if @curry.save
  #     redirect_to @curry
  #   else
  #     render "new"
  #   end
  # end

  def update
    if @curry.update(curry_params)
      render 'edit'
    else
      render 'edit'
    end
  end

  def show
  end


private

  def find_curry
    @curry = Curry.find(params[:id])
  end

  def curry_params
    params.require(:curry).permit(:title, :description, :monday, :tuesday, :wednesday, :thursday, :friday, :curry1, :curry2, :curry3, :curry4, :curry5, :date, :publish)
  end


end

app/helpers/curries_helper.rb
module CurriesHelper
end

app/views/curries/_form.html.erb
<%= simple_form_for(@curry) do |f| %>
  <%= f.error_notification %>

  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :monday %>
  <%= f.input :curry1 %>
  <%= f.input :tuesday %>
  <%= f.input :curry2 %>
  <%= f.input :wednesday %>
  <%= f.input :curry3 %>
  <%= f.input :thursday %>
  <%= f.input :curry4 %>
  <%= f.input :friday %>
  <%= f.input :curry5 %>

  <%= f.button :submit %>
<% end %>

app/views/curries/admin.html.erb
<h1>Curries#admin</h1>
<p>Find me in app/views/curries/admin.html.erb</p>

app/views/curries/edit.html.erb
<section class="section">

   <div class="container">

        <div class="row">

          <div class="col-md-10 col-md-offset-1">
            <%= link_to "<< Back to CMS Home", admin_dashboard_path %>
            <h2>Thai Curries of the Week</h2>
            <p>Edit the Thai Curries of the Week.</p>
          </div>



          <div class="col-md-10 col-md-offset-1 form-area">
          <%= simple_form_for(@curry) do |f| %>
            <%= f.error_notification %>
            <h4>Publish Curries?</h4>
            <%= f.input :publish, label: "Tick box to show Curries of the Week on the Live website" %>
          </div>
          <div class="col-md-10 col-md-offset-1 form-area">
            <%= f.input :title %>
            <%= f.input :date %>
            <%= f.input :description %>
          </div>
          <div class="col-md-10 col-md-offset-1 form-area">
            <%= f.input :curry1, label: "Monday" %>

            <%= f.input :curry2, label: "Tuesday" %>

            <%= f.input :curry3, label: "Wednesday" %>

            <%= f.input :curry4, label: "Thursday" %>

            <%= f.input :curry5, label: "Friday" %>

            <%= f.button :submit %>
          <% end %>
        </div>
        </div>
      </div>
</sectionn>

app/views/curries/index.html.erb
<h1>Curries#index</h1>
<p>Find me in app/views/curries/index.html.erb</p>

app/views/curries/new.html.erb
<section class="section">

   <div class="container">

        <div class="row">

          <div class="col-md-10 col-md-offset-1">
            <%= link_to "<< Back to Curries", curries_admin_path %>
            <h2>NEW Curries</h2>
            <p>Create a new curries mrnu.</p>
          </div>

          <%= render "form" %>

        </div>
      </div>
</sectionn>

app/views/curries/show.html.erb
<h1>Curries#show</h1>
<p>Find me in app/views/curries/show.html.erb</p>