config/routes.rb
Rails.application.routes.draw do










 as :user do
   get 'registrations/:id/edit' => 'registrations#edit', :as => :edit_user_profile
 end






  devise_for :users,
           :controllers  => {
             :registrations => 'registrations',

           }



  # get 'admins/:id/edit' => 'admins#edit', :as => :edit_admin


  root 'events#index'

  get 'admin/index' => 'admin#index'
  get 'admin/dashboard' => 'admin#dashboard'

  # get 'events/list' => 'events#list'

  get 'events/admin' => 'events#admin'

  get 'eats/admin' => 'eats#admin'
  get 'eats/index' => 'eats#index'

  get 'covers/index' => 'covers#index'

  get 'menus/:id/edit' => 'menus#edit'


  get 'curries/admin' => 'curries#admin'

  resources :events

  resources :eats

  resources :covers

  resources :curries

  resources :admin

  resources :menus

  resources :opening_hours









end

app/models/event.rb
 require 'date'

class Event < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader

  acts_as_list

  scope :is_cover, -> { where(cover: true) }
  scope :displayed_now, ->(date) {where("start_display <= ? AND end_display >= ?", date, date)}


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  require 'date'

  skip_before_action :authenticate_user!, only: :index

  layout "devise", only: [:admin, :new, :create, :show, :edit, :update, :destroy, :list]

  before_action :find_event, only: [:show, :edit, :update, :destroy]

  before_action :count_events, only: [:new, :create, :edit, :update]



  def index
    @events = Event.order(position: :asc)
    @eats = Eat.order(position: :asc)
    @cover = Cover.find(5)
    @event_cover = Event.is_cover.displayed_now(Date.today).first
    @curry = Curry.find(1)
    @menu_header = Menu.where(header: true).first
    @menu_special = Menu.where(special: true).first
    @opening_hours = OpeningHour.all
  end

   def admin
      @events = Event.order(position: :asc)
  end

  def new
    @event = Event.new
  end

  def create
   @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_admin_path
  end



  private

  def count_events
    @count = Event.where(publish: "Published").count + 1
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :subtitle, :body, :weekday, :day, :month, :year, :publish, :start, :end, :photo, :photo_cache, :cover, :event_icon, :event_title, :event_type, :position, :start_date, :end_date, :start_display, :end_display)
  end

end

app/helpers/events_helper.rb
require "date"


module EventsHelper



  # Checks if current day matches the weekday in the curry menu calendar
  # Returns red background class.
  def weekday_check(day)
    if
      Date.today.strftime("%A").downcase == day.downcase
      "bg-red-text-white"
    end
  end


  # Check if date today == date of event.
  # Must be inside .each loop with |event|
  def event_today?(event)
    Date.today == event.start_date
  end

  # Checks current time to see if Konrads is open
  def opening_times
      mon1 = @opening_hours.find(1).open_at
      mon2 = @opening_hours.find(1).open_until
      tue1 = @opening_hours.find(2).open_at
      tue2 = @opening_hours.find(2).open_until
      wed1 = @opening_hours.find(3).open_at
      wed2 = @opening_hours.find(3).open_until
      thu1 = @opening_hours.find(4).open_at
      thu2 = @opening_hours.find(4).open_until
      fri1 = @opening_hours.find(5).open_at
      fri2 = @opening_hours.find(5).open_until
      sat1 = @opening_hours.find(6).open_at
      sat2 = @opening_hours.find(6).open_until
      sun1 = @opening_hours.find(7).open_at
      sun2 = @opening_hours.find(7).open_until


      #Weekdays   Sun-0       Mon-1       Tues-2      Wed-3       Thu-4       Fri-5       Sat-6
      schedule = [[sun1,sun2],[mon1,mon2],[tue1,tue2],[wed1,wed2],[thu1,thu2],[fri1,fri2],[sat1,sat2]]
      # Weekday number Sun - Sat => 0 - 6
      day_num = Date.today.strftime("%w").to_i
      # The current hour. Ex.: 17:43 => 17
      time_now = Time.now.strftime("%H").to_i

      # Extract todas's and yesterday's opening hours from schedule
      todays_schedule = schedule[day_num]
      yesterdays_schedule = schedule[day_num - 1]

      # Check if its after (more than) 5AM right_now && if the shop is open (up until midnight)
      if time_now > 5 && (time_now >= todays_schedule[0] && time_now < 24)
        # FYI - '%.2f' transfroms a number into a 2 decimal float
          "Open now: #{'%.2f' % todays_schedule[0]} - #{'%.2f' % todays_schedule[1]}"
        # Elseif: Check closed past midnight YESTERDAY && if right_now is less than Closing time of schedule yesterday.
        elsif yesterdays_schedule[1] < 5 && time_now < yesterdays_schedule[1]
          "Open tonight until: #{'%.2f' % todays_schedule[1]} AM"
        # Else
        else
          "Closed now: #{'%.2f' % todays_schedule[0]} - #{'%.2f' % todays_schedule[1]}"
      end
   end

    # Match drop down terms in Events form with Font-Awsome icons
     def event_icon_helper(event_icon)
        icon = case event_icon
          when "music"
           "fa fa-music"
          when "comedy"
           "fa fa-smile-o"
          when "quiz"
           "fa fa-question-circle"
          when "party"
           "fa fa-glass"
          when "football"
           "fa fa-futbol-o"
          when "poetry"
           "fa fa-leaf"
          when "talk"
           "fa fa-commenting-o"
          when "magic"
           "fa fa-magic"
          when nil
           "<%= 'x' %>"
        end
      end

  # def event_count_helper
  #  0

  # end





end
# FINAL end TAG

app/views/events/sections/_admin_published.html.erb
 <div class="circle circle-green col-xs-2">LIVE</div>
                  <div class="col-xs-10"><h3>Published Events</h3></div>
                  <div class="col-xs-12">
                  <% @events.each do |event| %>
                    <% if event.publish == "Published" %>
                      <hr>

                      <!-- Status indicators -->
                      <div class="col-md-12 row">
                        <div class="col-md-2 table-box-gray">
                          Position: <%= event.position %>
                        </div>
                        <div class="col-md-2 table-box-gray">
                          Is Cover?: <%= event.cover %>
                        </div>
                        <% if event.cover == true %>
                          <div class="col-md-6 table-box-gray">
                            Cover Dates: <%= event.start_display.try(:strftime,'%a, %d %b %y') %>  -  <%= event.end_display.try(:strftime,'%a, %d %b %y') %>
                          </div>
                        <% end %>
                      </div>



                      <!-- Events Card start -->
                      <div class="bubble col-md-12 ">

                        <!-- Display Today Ribbon if event is today-->
                        <% if event_today?(event) %>
                           <div class="corner-ribbon top-right">Tonight</div>
                           <div class="hide-corner-top"></div>
                           <div class="hide-corner-right"></div>
                        <% end %>
                        <!-- Card content start -->
                        <div class="col-md-7">
                          <h3><i class="<%= event_icon_helper(event.event_icon) %>"aria-hidden='true'></i>
                            <%= event.title %></h3>
                          <h4><%= event.start_date.try(:strftime,'%A, %d %b %Y') %>, <%= event.start %>-<%= event.end %></h4>
                          <p> <strong><%= event.subtitle %></strong></p>
                          <div class="text">
                            <p><%= simple_format(event.body.html_safe) %></p>
                          </div>
                        </div>
                        <!-- Event Image -->
                        <div class="col-md-5 ">
                          <!-- image_tag "p9.jpg", {class: "img-responsive"} -->
                          <%= cl_image_tag event.photo,  {class: "img-responsive"}  %>
                        </div>


                        <!-- Add DATE to CAlendar -->

                        <div class="col-md-7">
                          <div title="Add to Calendar" class="addeventatc">
                            Add to Calendar
                            <span class="start"><%= event.start_date.try(:strftime,'%d/%m/%Y') %> <%= event.start %></span>
                            <span class="end"><%= event.end_date.try(:strftime,'%d/%m/%Y') %>  <%= event.end %></span>
                            <span class="timezone">Europe/Luxembourg</span>
                            <span class="title"><%= event.title %></span>
                            <span class="description"><%= event.subtitle %></span>
                            <span class="location"><%= event.address_one %></span>
                            <span class="date_format">DD/MM/YYYY</span>
                          </div>
                        </div>


                        <!-- Ribbon "Rectangle" with day and month -->
                        <div class="rectangle">
                          <!-- Code below uses "squar_month()" helper -->
                          <p><%= event.start_date.try(:strftime,'%d') %>
                            <br><%= event.start_date.try(:strftime,'%b').to_s.upcase %></p>
                        </div>
                        <!-- Ribbon shaded "triangle" -->
                        <div class="triangle-l"></div>
                      </div>
                      <!-- Events Card End -->




                      <br>
                      <i class="icon-md ion-ios-eye"></i>


                      <h4><%= link_to " Edit Event", edit_event_path(event) %> |
                      <%= link_to " Delete Event", event_path(event), method: :delete, data: {confirm: "Are you sure you want to delete?"} %></h4>
                    <% end %>
                  <% end %>
                </div>

app/views/events/sections/_admin_unpublished.html.erb
 <div class="circle circle-red col-xs-2">NOPE</div>
                  <div class="col-xs-10"><h3>NON-Published Events</h3></div>
                  <div class="col-xs-12">
                  <% @events.each do |event| %>
                    <% if event.publish == "Not Published" %>
                      <hr>

                      <!-- Status indicators -->
                      <div class="col-md-12 row">
                        <div class="col-md-2 table-box-gray">
                          Position: <%= event.position %>
                        </div>
                        <div class="col-md-2 table-box-gray">
                          Is Cover?: <%= event.cover %>
                        </div>
                        <% if event.cover == true %>
                          <div class="col-md-6 table-box-gray">
                            Cover Dates: <%= event.start_display.try(:strftime,'%a, %d %b %y') %>  -  <%= event.end_display.try(:strftime,'%a, %d %b %y') %>
                          </div>
                        <% end %>
                      </div>



                      <!-- Events Card start -->
                      <div class="bubble col-md-12 ">

                        <!-- Display Today Ribbon if event is today-->
                        <% if event_today?(event) %>
                           <div class="corner-ribbon top-right">Tonight</div>
                           <div class="hide-corner-top"></div>
                           <div class="hide-corner-right"></div>
                        <% end %>
                        <!-- Card content start -->
                        <div class="col-md-7">
                          <h3><i class="<%= event_icon_helper(event.event_icon) %>"aria-hidden='true'></i>
                            <%= event.title %></h3>
                          <h4><%= event.start_date.try(:strftime,'%A, %d %b %Y') %>, <%= event.start %>-<%= event.end %></h4>
                          <p> <strong><%= event.subtitle %></strong></p>
                          <div class="text">
                            <p><%= simple_format(event.body.html_safe) %></p>
                          </div>
                        </div>
                        <!-- Event Image -->
                        <div class="col-md-5 ">
                          <!-- image_tag "p9.jpg", {class: "img-responsive"} -->
                          <%= cl_image_tag event.photo,  {class: "img-responsive"}  %>
                        </div>


                        <!-- Add DATE to CAlendar -->

                        <div class="col-md-7">
                          <div title="Add to Calendar" class="addeventatc">
                            Add to Calendar
                            <span class="start"><%= event.start_date.try(:strftime,'%d/%m/%Y') %> <%= event.start %></span>
                            <span class="end"><%= event.end_date.try(:strftime,'%d/%m/%Y') %>  <%= event.end %></span>
                            <span class="timezone">Europe/Luxembourg</span>
                            <span class="title"><%= event.title %></span>
                            <span class="description"><%= event.subtitle %></span>
                            <span class="location"><%= event.address_one %></span>
                            <span class="date_format">DD/MM/YYYY</span>
                          </div>
                        </div>


                        <!-- Ribbon "Rectangle" with day and month -->
                        <div class="rectangle">
                          <!-- Code below uses "squar_month()" helper -->
                          <p><%= event.start_date.try(:strftime,'%d') %>
                            <br><%= event.start_date.try(:strftime,'%b').to_s.upcase %></p>
                        </div>
                        <!-- Ribbon shaded "triangle" -->
                        <div class="triangle-l"></div>
                      </div>
                      <!-- Events Card End -->




                      <br>
                      <i class="icon-md ion-ios-eye"></i>


                      <h4><%= link_to " Edit Event", edit_event_path(event) %> |
                      <%= link_to " Delete Event", event_path(event), method: :delete, data: {confirm: "Are you sure you want to delete?"} %></h4>
                    <% end %>
                  <% end %>
                </div>

app/views/events/sections/_contact_form.html.erb
 <div class="col-md-6 wow ">

            <form id="contact-form" role="form">

              <div class="form-group">
                <label class="sr-only" for="c_name">Name</label>
                <input type="text" id="c_name" class="form-control" name="c_name" placeholder="Name">
              </div>

              <div class="form-group">
                <label class="sr-only" for="c_email">Email address</label>
                <input type="email" id="c_email" class="form-control" name="c_email" placeholder="E-mail">
              </div>

              <div class="form-group">
                <textarea class="form-control" id="c_message" name="c_message" rows="7" placeholder="Your message"></textarea>
              </div>

              <button type="submit" class="btn btn-custom-1">
                <i class="fa fa-bullhorn icon-before"></i> Send it
              </button>

            </form>

            <div class="ajax-response"></div>

          </div>

app/views/events/sections/_cover_image1.html.erb
  <section id="intro" class="section cl-image-bg"
      style="background-image:
      linear-gradient(rgba(0,0,0,0.3),
      rgba(0,0,0,0.2)),
      url('<%= cl_image_path @event_cover.photo, height: 1200, width: 1600 %>');
      background-color: #222; ">

app/views/events/sections/_cover_image2.html.erb
<section id="intro" class="section cl-image-bg"
      style="background-image:
      linear-gradient(rgba(0,0,0,0.3),
      rgba(0,0,0,0.2)),
      url('<%= cl_image_path @cover.cover_photo, height: 1200, width: 1600 %>');
      background-color: #222;">

app/views/events/sections/_cover_info1.html.erb
<div class="col-md-4 ">
    <div class="infobox wow bg-shade-medium">
      <h3></i><%= @event_cover.start_date.strftime("%a, %d %b %Y") %>, <%= @event_cover.start %>-<%= @event_cover.end%></h3>
      <h3><%= @event_cover.event_type %></h3>
      <h2><%= @event_cover.title %></h2>
      <!-- Info Button -->
      <h3> <a href="#events" class="btn  btn-custom-3 callout-btn"><i class="fa fa-info-circle icon-before"></i> Info</a>
      </h3>

    </div>
  </div>

app/views/events/sections/_curry.html.erb
    <section id="thai-curry" class="section bg-lite-grey curry-bg">
      <div class="container ">
        <div class="row">
          <!-- Curry logo -->
          <div class="col-md-2  col-md-offset-1">
            <%= image_tag "curry-logo.png", {class: "img-responsive curry"}%>
          </div>
          <!-- Curry title-->
          <div class="col-md-6 text-center">
            <div class="headline">
              <h3><%= @curry.title %></h3>
              <h4><%= @curry.date %></h4>
              <p><%= @curry.description %></p>
            </div>
          </div>
          <!-- curry boxes -->
          <div class="col-md-12 ">
            <!-- Below: "weekday_check" helper highlights current weekday -->
            <div class="col-md-5th col-sm-6">
              <div class="curry-head">Monday</div>
              <div class="curry-box <%= weekday_check("monday") %>"
                ><%= @curry.curry1 %>
              </div>
            </div>
            <div class="col-md-5th col-sm-6">
              <div class="curry-head">Tuesday</div>
              <div class="curry-box <%= weekday_check("tuesday") %>">
                <%= @curry.curry2 %>
              </div>
            </div>
            <div class="col-md-5th col-sm-6">
              <div class="curry-head">Wednesday</div>
              <div class="curry-box <%= weekday_check("wednesday") %>">
                <%= @curry.curry3 %>
              </div>
            </div>
            <div class="col-md-5th col-sm-6">
              <div class="curry-head">Thursday</div>
              <div class="curry-box <%= weekday_check("thursday") %>">
                <%= @curry.curry4 %></div>
            </div>
            <div class="col-md-5th col-sm-6">
              <div class="curry-head">Friday</div>
              <div class="curry-box <%= weekday_check("friday") %>">
                <%= @curry.curry5 %>
              </div>
            </div>

          </div> <!-- end curry boxes -->


        </div><!-- .row -->

      </div><!-- .container -->

    </section>

app/views/events/sections/_events.html.erb
    <section id="events" class="section">

      <div class="container">


        <div class="row">

          <div class="col-md-12 headline wow ">
            <h2>Events</h2>
            <p>Upcoming concerts and other live acts</p>
          </div>

          <div class="col-md-12">
            <div class="row">
            <% @events.each do |event| %>
             <% if event.publish == "Published"%>

             <!-- Events Card start -->
              <div class="bubble col-md-12 align-left">

                <!-- Display Today Ribbon if event is today-->
                <% if event_today?(event) %>
                   <div class="corner-ribbon top-right">Tonight</div>
                   <div class="hide-corner-top"></div>
                   <div class="hide-corner-right"></div>
                <% end %>
                <!-- Card content start -->
                <div class="col-md-7">
                  <h3><i class="<%= event_icon_helper(event.event_icon) %>"aria-hidden='true'></i>
                    <%= event.title %></h3>
                  <h4><%= event.start_date.try(:strftime,'%A, %d %b %Y') %>, <%= event.start %>-<%= event.end %></h4>
                  <p> <strong><%= event.subtitle %></strong></p>
                  <div class="text">
                    <p><%= simple_format(event.body.html_safe) %></p>
                  </div>
                </div>
                <!-- Event Image -->
                <div class="col-md-5">
                  <!-- image_tag "p9.jpg", {class: "img-responsive"} -->
                  <%= cl_image_tag event.photo,  {class: "img-responsive event-img-xs"}  %>
                </div>


                <!-- Add DATE to CAlendar -->

                <div class="col-md-7">
                  <div title="Add to Calendar" class="addeventatc">
                    Add to Calendar
                    <span class="start"><%= event.start_date.try(:strftime,'%d/%m/%Y') %> <%= event.start %></span>
                    <span class="end"><%= event.end_date.try(:strftime,'%d/%m/%Y') %>  <%= event.end %></span>
                    <span class="timezone">Europe/Luxembourg</span>
                    <span class="title"><%= event.title %></span>
                    <span class="description"><%= event.subtitle %></span>
                    <span class="location"><%= event.address_one %></span>
                    <span class="date_format">DD/MM/YYYY</span>
                  </div>
                </div>


                <!-- Ribbon "Rectangle" with day and month -->
                <div class="rectangle">
                  <!-- Code below uses "squar_month()" helper -->
                  <p><%= event.start_date.try(:strftime,'%d') %>
                    <br><%= event.start_date.try(:strftime,'%b').to_s.upcase %></p>
                </div>
                <!-- Ribbon shaded "triangle" -->
                <div class="triangle-l"></div>
              </div>
              <!-- Events Card End -->
                 <% end %>
               <% end %>
            </div>
          </div>



        </div><!-- .row -->

      </div><!-- .container -->

    </section>

app/views/events/sections/_events2.html.erb
 <section id="events" class="section">

      <div class="container">


        <div class="row">

          <div class="col-md-12 headline wow ">
            <h2>Events</h2>
            <p>Upcoming concerts and other live acts</p>
          </div>

         <div class='dsm-fb-event' embed-id='2134'></div><script src='https://www.displaysocialmedia.com/app/embed/facebook-events/widget.js'></script>



        </div><!-- .row -->

      </div><!-- .container -->

    </section>

app/views/events/sections/_opening_hours.html.erb
  <div class="col-md-6">
    <h4><i class="fa fa-clock-o"></i> Opening Hours:</h4>

      <div class="col-xs-2 row">
        <ul class="nodeco-list">
          <li>Mon: </li>
          <li>Tue: </li>
          <li>Wed: </li>
          <li>Thu: </li>
        </ul>
      </div>

      <div class="col-xs-4 ">
        <ul class="nodeco-list">
          <li><%='%.02f' % @opening_hours.find(1).open_at %> - <%='%.02f' % @opening_hours.find(1).open_until %></li>
          <li><%='%.02f' % @opening_hours.find(2).open_at %> - <%='%.02f' % @opening_hours.find(2).open_until %></li>
          <li><%='%.02f' % @opening_hours.find(3).open_at %> - <%='%.02f' % @opening_hours.find(3).open_until %></li>
          <li><%='%.02f' % @opening_hours.find(4).open_at %> - <%='%.02f' % @opening_hours.find(4).open_until %></li>
       </ul>
      </div>

      <div class="col-xs-2 row">
        <ul class="nodeco-list">
          <li>Fri: </li>
          <li>Sat: </li>
          <li>Sun: </li>
        </ul>
      </div>


      <div class="col-xs-4 ">
        <ul class="nodeco-list">
          <li><%='%.02f' % @opening_hours.find(5).open_at %> - <%='%.02f' % @opening_hours.find(5).open_until %></li>
          <li><%='%.02f' % @opening_hours.find(6).open_at %> - <%='%.02f' % @opening_hours.find(6).open_until %></li>
          <li><%='%.02f' % @opening_hours.find(7).open_at %> - <%='%.02f' % @opening_hours.find(7).open_until %></li>
       </ul>
      </div>


  </div>

app/views/events/sections/_parallax01.html.erb
  <section class=" parallax01">

      <div class="container ">

        <div class="row">



          <div class="col-md-6 col-md-offset-3  ">
            <h1><i class="fa fa-cutlery" aria-hidden="true"></i></h1>
            <h3><p>Our food: Delicious, helathy, local & Organic.</p>

          </div>

        </div><!-- .row -->

      </div><!-- .container -->

    </section>

app/views/events/sections/_photo_gallery.html.erb
    <!-- Photo Gallery section start -->

    <section id="portfolio" class="section">

      <div class="container">

        <div class="row">

          <div class="col-md-12 headline wow">
            <h2>Image Gallery</h2>
            <p>Lorem Ipsum.</p>
          </div>




           <!-- Nav tabs -->
            <ul class="nav nav-tabs">
              <li class="active"><a href="#tab1" data-toggle="tab">2015</a></li>
              <li><a href="#tab2" data-toggle="tab">2014</a></li>
              <li><a href="#tab3" data-toggle="tab">2013</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content long-down">


              <!-- Tab 1 content begins -->
              <div class="tab-pane active" id="tab1">



          <div class="col-md-4 col-sm-6 wow">
            <a href="assets/images/p1.jpg" class="pop-up" title="Caption 1">
              <div class="portfolio-item">
                <div class="portfolio-item-preview">
                  <img src="assets/images/p1.jpg" alt="">
                </div>
                <div class="portfolio-item-description">
                  <h3>Some work</h3>
                  <p>Category</p>
                </div>
              </div>
            </a>
          </div>

          <div class="col-md-4 col-sm-6 wow">
            <a href="https://vimeo.com/45830194" class="video-pop-up" title="Caption 2">
              <div class="portfolio-item">
                <div class="portfolio-item-preview">
                  <img src="assets/images/p2.jpg" alt="">
                </div>
                <div class="portfolio-item-description">
                  <h3>Some work</h3>
                  <p>Category</p>
                </div>
              </div>
            </a>
          </div>

          <div class="col-md-4 col-sm-6 wow">
            <a href="assets/images/p3.jpg" class="pop-up" title="Caption 3">
              <div class="portfolio-item">
                <div class="portfolio-item-preview">
                  <img src="assets/images/p3.jpg" alt="">
                </div>
                <div class="portfolio-item-description">
                  <h3>Some work</h3>
                  <p>Category</p>
                </div>
              </div>
            </a>
          </div>

          <div class="col-md-4 col-sm-6 wow" data-wow-delay=".2s">
            <a href="assets/images/p5.jpg" class="pop-up" title="Caption 4">
              <div class="portfolio-item">
                <div class="portfolio-item-preview">
                  <img src="assets/images/p5.jpg" alt="">
                </div>
                <div class="portfolio-item-description">
                  <h3>Some work</h3>
                  <p>Category</p>
                </div>
              </div>
            </a>
          </div>

          <div class="col-md-4 col-sm-6 wow" data-wow-delay=".4s">
            <a href="assets/images/p8.jpg" class="pop-up" title="Caption 5">
              <div class="portfolio-item">
                <div class="portfolio-item-preview">
                  <img src="assets/images/p8.jpg" alt="">
                </div>
                <div class="portfolio-item-description">
                  <h3>Some work</h3>
                  <p>Category</p>
                </div>
              </div>
            </a>
          </div>

          <div class="col-md-4 col-sm-6 wow" data-wow-delay=".6s">
            <a href="assets/images/p6.jpg" class="pop-up" title="Caption 6">
              <div class="portfolio-item">
                <div class="portfolio-item-preview">
                  <img src="assets/images/p6.jpg" alt="">
                </div>
                <div class="portfolio-item-description">
                  <h3>Some work</h3>
                  <p>Category</p>
                </div>
              </div>
            </a>
          </div>

          </div>

               <!-- Tab 2 content begins -->
              <div class="tab-pane" id="tab2">Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</div>

               <!-- Tab 3 content begins -->
              <div class="tab-pane" id="tab3">Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth.</div>
            </div> <!-- Tab section end -->



        </div><!-- .row -->

      </div><!-- .container -->

    </section>

    <!-- Photo Gallery section end -->

app/views/events/sections/_test.html.erb
<section id="events" class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <% @events.each do |event| %>
                <!-- Card content start -->
                <div class="col-md-7">

                  <h4><%= event.start_date.try(:strftime, '%A, %d %b %Y') %></h4>

                </div>
                <% end %>
            </div>
          </div>
          <!-- Events Card End -->
        </div><!-- .row -->
      </div><!-- .container -->
    </section>

app/views/events/sections/_todays_specials.html.erb
   <!-- Today's special section-->

            <div class="col-xs-12 lunch-special">
              <div class="col-xs-2">
                <h3><i class="fa fa-star-o" aria-hidden="true"></i></h3>
              </div>
              <div class="col-xs-8">
                <h3><%= @menu_special.title %></h3>
                <h4><%= @menu_special.subtitle %></h4>
              </div>
              <div class="col-xs-2">
                <h3><i class="fa fa-star-o" aria-hidden="true"></i></h3>
              </div>
            </div>

       <!-- End Today's specials -->