config/routes.rb
Rails.application.routes.draw do










 as :user do
   get 'registrations/:id/edit' => 'registrations#edit', :as => :edit_user_profile
 end






  devise_for :users,
           :controllers  => {
             :registrations => 'registrations',

           }



  # get 'admins/:id/edit' => 'admins#edit', :as => :edit_admin


  root 'events#index'

  get 'admin/index' => 'admin#index'
  get 'admin/dashboard' => 'admin#dashboard'

  # get 'events/list' => 'events#list'

  get 'events/admin' => 'events#admin'

  get 'eats/admin' => 'eats#admin'
  get 'eats/index' => 'eats#index'

  get 'covers/index' => 'covers#index'

  get 'menus/:id/edit' => 'menus#edit'


  get 'curries/admin' => 'curries#admin'

  resources :events

  resources :eats

  resources :covers

  resources :curries

  resources :admin

  resources :menus

  resources :opening_hours









end

app/models/eat.rb
class Eat < ActiveRecord::Base
   acts_as_list
end

app/controllers/eats_controller.rb
class EatsController < ApplicationController

layout "devise", only: [:index, :admin, :new, :create, :show, :edit, :update, :destroy]

  before_action :find_eat, only: [:show, :edit, :update, :destroy]

  def index
    @eats = Eat.order(position: :asc)
    @menu_header = Menu.where(header: true).first
    @menu_special = Menu.where(special: true).first
  end


   def admin
      @eats = Eat.all
  end

  def new
    @eat = Eat.new
  end

  def create
   @eat = Eat.new(eat_params)
    if @eat.save
      redirect_to @eat
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @eat.update(eat_params)
      redirect_to eats_index_path
    else
      render 'edit'
    end
  end

  def destroy
    @eat.destroy
    redirect_to eats_admin_path
  end



  private

  def find_eat
    @eat = Eat.find(params[:id])
  end

  def eat_params
    params.require(:eat).permit(:header, :subheader, :title, :subtitle, :body, :position, :menu_icon)
  end

end

app/helpers/eats_helper.rb
module EatsHelper

  # Match drop down terms in Eats form with Font-Awsome icons
     def menu_icon_helper(event_icon)
        icon = case event_icon
          when "coffee"
           "fa fa-coffee"
          when "juice"
           "fa fa-apple"
          when "beer"
           "fa fa-beer"
          when "wine"
           "fa fa-glass"
          when "spirit"
           "fa fa-flask"
          when "pie"
           "fa fa-pie-chart"
          when "salad"
           "fa fa-leaf"
          when "sandwich"
           "fa fa-bars"
          when nil
           "<%= 'x' %>"
        end
      end

end

app/views/eats/_form.html.erb
<%= simple_form_for(@eat) do |f| %>
  <%= f.error_notification %>

  <!-- Position -->
  <div class="col-md-12  form-area">
    <h3><i class="fa fa-arrows-v" aria-hidden="true"></i> Change Position Menu Item?</h3>
    <p>Positions 1-5 will be shown in Column 1, and 6-10 in Column 2.</p>
    <%= f.input_field :position, :collection => (1..8) %>
  </div>

<!-- Main content -->
<div class="col-md-12  form-area">
  <div class="col-xs-2">
     <%= f.input :menu_icon, :collection => ['coffee', 'juice', 'beer', 'wine', 'spirit', 'pie', 'salad', 'sandwich' ], label: "Icons" %>
  </div>
  <%= f.input :title %>
  <%= f.input :body %>
</div>



<!-- Button -->
<div class="col-md-12 row ">
  <%= f.button :submit, "Update Menu Item" %>
</div>

<% end %>

app/views/eats/admin.html.erb
<section class="section">

  <div class="container">

    <div class="row">
      <div class="col-md-12 long-down">
        <h3>Eat and Drink page</h3>
        <%= link_to edit_eat_path(@eats.last) , class: "btn-treehouse btn-md" do %>
        <i class="fa fa-pencil"> Edit the content below </i>
        <%end%>
      </div>
    </div><!-- row -->





        <div class="row">

          <div class="col-md-12 headline">

            <hr>
            <% eat = @eats.last%>
            <h2><%= eat.header %></h2>
            <p><%=  eat.subheader %></p>
          </div>

          <div class="col-md-3 col-sm-6 hidden-xs wow ">
            <%= image_tag "foodie500_01.jpg", {class: "avatar"}%>
          </div>

          <div class="col-md-3 col-sm-6 hidden-xs wow ">
             <%= image_tag "foodie500_02.jpg", {class: "avatar"}%>
          </div>

          <div class="col-md-6 col-sm-12">
            <h3><%=  eat.title %></h3>
            <h4><%=  eat.subtitle %></h4>
            <p><%=   eat.body %></p>
          </div>
        </div><!-- row-->


  </div><!-- container-->
</section>

app/views/eats/edit.html.erb
<section class="section">

   <div class="container">

        <div class="row">

          <div class="col-md-10 col-md-offset-1">

            <h3>Edit Eat Menu Item </h3>


            <%= render 'form' %>

          </div>
        </div>
      </div>
</sectionn>

app/views/eats/index.html.erb
<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-xs-10 col-md-offset-1 centered">
        <h2><%= @menu_header.title %></h2>
        <h4><%= @menu_header.subtitle %></h4>
         <%= link_to "Edit Headers", edit_menu_path(@menu_header) %>
      </div>


      <div class="col-xs-10 col-md-offset-1 form-area">
          <h3>Eat and Drink Menu</h3>

          <!-- ******* Published Events ******* -->

          <!-- Column 1 -->
          <div class="col-md-6 ">
            <div class="col-xs-12 line-text-top">
              <h3>Menu Colum 1</h3>
              <hr>
              <% @eats.each do |item| %>
                <% if item.position <= 5 %>
                  <div class="dotted-underlinez">
                    <h4>Position: <%= item.position %></h4>
                    <h4><i class="<%= menu_icon_helper(item.menu_icon) %>"aria-hidden='true'></i> <%= item.title %></h4>
                    <p><%=  item.body %></p>
                    <%= link_to " Edit Menu Item", edit_eat_path(item) %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
          <!-- Coulm 1 End -->

          <!-- Column 2 -->
          <div class="col-md-6">
            <div class="col-xs-12 line-text-top">
              <h3>Menu Colum 2</h3>
              <hr>
              <% @eats.each do |item| %>
                  <% if item.position >= 6 && item.position <= 10 %>
                    <div class="dotted-underlinez">
                      <h4>Position: <%= item.position %></h4>
                      <h4><i class="<%= menu_icon_helper(item.menu_icon) %>"aria-hidden='true'></i> <%= item.title %></h4>
                      <p><%=  item.body %></p>
                      <%= link_to " Edit Menu Item", edit_eat_path(item) %>
                    </div>
                  <% end %>
              <% end %>
            </div>
          </div>
          <!-- Colum 2 End -->

          <!-- Today's special section-->
          <div class="col-md-6">
            <p>Publish Status of "Today's Special": <strong><%= @menu_special.publish.to_s.upcase %></strong></p>
            <div class="col-xs-12 lunch-special">
              <div class="col-xs-2">
                <h3><i class="fa fa-star-o" aria-hidden="true"></i></h3>
              </div>
              <div class="col-xs-8">
                <h3><i class="fa fa-cutlery" aria-hidden="true"></i>
                <%= @menu_special.title %></h3>
                <h4><%= @menu_special.subtitle %></h4>
              </div>
              <div class="col-xs-2">
                <h3><i class="fa fa-star-o" aria-hidden="true"></i></h3>
              </div>
            </div>
              <%= link_to "Edit Today's Special", edit_menu_path(@menu_special) %>
          </div>
       <!-- End Today's specials -->


      </div>

    </div>
  </div>
</section>

app/views/eats/new.html.erb
<section class="section">

   <div class="container">

        <div class="row">

          <div class="col-md-12">

            <h1>Eat & Drink: New</h1>
            <p>This is a new events page</p>

            <%= render 'form' %>

          </div>
        </div>
      </div>
</sectionn>

app/views/eats/show.html.erb
<section class="section">

   <div class="container">

        <div class="row">

          <div class="col-md-12 headline">
            <i class="fa fa-pencil"></i> <%=link_to "Edit", edit_eat_path, 'data-no-turbolink' => true  %>
             <hr>

            <h2><%=  @eat.header %></h2>
            <p><%=  @eat.subheader %></p>
          </div>

          <div class="col-md-3 col-sm-6 hidden-xs wow ">
            <%= image_tag "foodie500_01.jpg", {class: "avatar"}%>
          </div>

          <div class="col-md-3 col-sm-6 hidden-xs wow ">
             <%= image_tag "foodie500_02.jpg", {class: "avatar"}%>
          </div>

          <div class="col-md-6 col-sm-12">
            <h3><%=  @eat.title %></h3>
            <h4><%=  @eat.subtitle %></h4>
            <p><%=   @eat.body %></p>
          </div>
        </div>
      </div>
</section>

app/views/eats/update.html.erb
<h1>Eats#update</h1>
<p>Find me in app/views/eats/update.html.erb</p>