config/routes.rb
Rails.application.routes.draw do










 as :user do
   get 'registrations/:id/edit' => 'registrations#edit', :as => :edit_user_profile
 end






  devise_for :users,
           :controllers  => {
             :registrations => 'registrations',

           }



  # get 'admins/:id/edit' => 'admins#edit', :as => :edit_admin


  root 'events#index'

  get 'admin/index' => 'admin#index'
  get 'admin/dashboard' => 'admin#dashboard'

  # get 'events/list' => 'events#list'

  get 'events/admin' => 'events#admin'

  get 'eats/admin' => 'eats#admin'
  get 'eats/index' => 'eats#index'

  get 'covers/index' => 'covers#index'

  get 'menus/:id/edit' => 'menus#edit'


  get 'curries/admin' => 'curries#admin'

  resources :events

  resources :eats

  resources :covers

  resources :curries

  resources :admin

  resources :menus

  resources :opening_hours









end

app/models/cover.rb
class Cover < ActiveRecord::Base
  mount_uploader :cover_photo, CoverPhotoUploader
end

app/models/curry.rb
class Curry < ActiveRecord::Base
end

app/models/eat.rb
class Eat < ActiveRecord::Base
   acts_as_list
end

app/models/event.rb
 require 'date'

class Event < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader

  acts_as_list

  scope :is_cover, -> { where(cover: true) }
  scope :displayed_now, ->(date) {where("start_display <= ? AND end_display >= ?", date, date)}


end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/opening_hour.rb
class OpeningHour < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable:

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  # after_create :send_admin_mail
  # def send_admin_mail
  #   AdminMailer.new_user_waiting_for_approval(self).deliver
  # end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end




end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  layout "devise"
  before_action :find_event, only: [:show]

  def dashboard
  end

  def index
    if params[:approved] == "false"
      @users = User.where(approved: false)
    else
      @users = User.all
    end
  end

  def show
  end


private

  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :subtitle, :body, :weekday, :day, :month, :year, :publish, :start, :end)
  end




end

app/controllers/eats_controller.rb
class EatsController < ApplicationController

layout "devise", only: [:index, :admin, :new, :create, :show, :edit, :update, :destroy]

  before_action :find_eat, only: [:show, :edit, :update, :destroy]

  def index
    @eats = Eat.order(position: :asc)
    @menu_header = Menu.where(header: true).first
    @menu_special = Menu.where(special: true).first
  end


   def admin
      @eats = Eat.all
  end

  def new
    @eat = Eat.new
  end

  def create
   @eat = Eat.new(eat_params)
    if @eat.save
      redirect_to @eat
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @eat.update(eat_params)
      redirect_to eats_index_path
    else
      render 'edit'
    end
  end

  def destroy
    @eat.destroy
    redirect_to eats_admin_path
  end



  private

  def find_eat
    @eat = Eat.find(params[:id])
  end

  def eat_params
    params.require(:eat).permit(:header, :subheader, :title, :subtitle, :body, :position, :menu_icon)
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  layout "devise"

   before_action :find_menu, only: [:edit, :update]

  def edit
  end

  def update
    if @menu.update(menu_params)
      redirect_to eats_index_path
    else
      render 'edit'
    end
  end


  private

  def find_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit(:title, :subtitle, :header, :special, :publish)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/covers_helper.rb
module CoversHelper
end

app/helpers/curries_helper.rb
module CurriesHelper
end

app/helpers/eats_helper.rb
module EatsHelper

  # Match drop down terms in Eats form with Font-Awsome icons
     def menu_icon_helper(event_icon)
        icon = case event_icon
          when "coffee"
           "fa fa-coffee"
          when "juice"
           "fa fa-apple"
          when "beer"
           "fa fa-beer"
          when "wine"
           "fa fa-glass"
          when "spirit"
           "fa fa-flask"
          when "pie"
           "fa fa-pie-chart"
          when "salad"
           "fa fa-leaf"
          when "sandwich"
           "fa fa-bars"
          when nil
           "<%= 'x' %>"
        end
      end

end

app/helpers/events_helper.rb
require "date"


module EventsHelper



  # Checks if current day matches the weekday in the curry menu calendar
  # Returns red background class.
  def weekday_check(day)
    if
      Date.today.strftime("%A").downcase == day.downcase
      "bg-red-text-white"
    end
  end


  # Check if date today == date of event.
  # Must be inside .each loop with |event|
  def event_today?(event)
    Date.today == event.start_date
  end

  # Checks current time to see if Konrads is open
  def opening_times
      mon1 = @opening_hours.find(1).open_at
      mon2 = @opening_hours.find(1).open_until
      tue1 = @opening_hours.find(2).open_at
      tue2 = @opening_hours.find(2).open_until
      wed1 = @opening_hours.find(3).open_at
      wed2 = @opening_hours.find(3).open_until
      thu1 = @opening_hours.find(4).open_at
      thu2 = @opening_hours.find(4).open_until
      fri1 = @opening_hours.find(5).open_at
      fri2 = @opening_hours.find(5).open_until
      sat1 = @opening_hours.find(6).open_at
      sat2 = @opening_hours.find(6).open_until
      sun1 = @opening_hours.find(7).open_at
      sun2 = @opening_hours.find(7).open_until


      #Weekdays   Sun-0       Mon-1       Tues-2      Wed-3       Thu-4       Fri-5       Sat-6
      schedule = [[sun1,sun2],[mon1,mon2],[tue1,tue2],[wed1,wed2],[thu1,thu2],[fri1,fri2],[sat1,sat2]]
      # Weekday number Sun - Sat => 0 - 6
      day_num = Date.today.strftime("%w").to_i
      # The current hour. Ex.: 17:43 => 17
      time_now = Time.now.strftime("%H").to_i

      # Extract todas's and yesterday's opening hours from schedule
      todays_schedule = schedule[day_num]
      yesterdays_schedule = schedule[day_num - 1]

      # Check if its after (more than) 5AM right_now && if the shop is open (up until midnight)
      if time_now > 5 && (time_now >= todays_schedule[0] && time_now < 24)
        # FYI - '%.2f' transfroms a number into a 2 decimal float
          "Open now: #{'%.2f' % todays_schedule[0]} - #{'%.2f' % todays_schedule[1]}"
        # Elseif: Check closed past midnight YESTERDAY && if right_now is less than Closing time of schedule yesterday.
        elsif yesterdays_schedule[1] < 5 && time_now < yesterdays_schedule[1]
          "Open tonight until: #{'%.2f' % todays_schedule[1]} AM"
        # Else
        else
          "Closed now: #{'%.2f' % todays_schedule[0]} - #{'%.2f' % todays_schedule[1]}"
      end
   end

    # Match drop down terms in Events form with Font-Awsome icons
     def event_icon_helper(event_icon)
        icon = case event_icon
          when "music"
           "fa fa-music"
          when "comedy"
           "fa fa-smile-o"
          when "quiz"
           "fa fa-question-circle"
          when "party"
           "fa fa-glass"
          when "football"
           "fa fa-futbol-o"
          when "poetry"
           "fa fa-leaf"
          when "talk"
           "fa fa-commenting-o"
          when "magic"
           "fa fa-magic"
          when nil
           "<%= 'x' %>"
        end
      end

  # def event_count_helper
  #  0

  # end





end
# FINAL end TAG

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/opening_hours_helper.rb
module OpeningHoursHelper
end

app/views/admin/dashboard.html.erb
<section class="section">
  <div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">


<h2>Konrad CMC Home</h2>


</div>
</div>
</section>

app/views/admin/index.html.erb
<section class="section">
  <div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">

        <h2>List of users</h2>

        <div>

          <h3>Approved Users</h3>
          <% @users.each do |user| %>
              <% if user.approved  %>
              <div>  <%= user.email %></div>

              <% end %>
          <% end %>
          <br><br>

          <h3>Un-approved Users</h3>
          <% @users.each do |user| %>
              <% if (user.approved  == false)  %>
              <div>  <%= "Email: #{user.email} "%></div>
              <div><%= "ID: #{user.id}" %></div>
              <div><%= "Status: #{user.approved}" %><br><br><div>



              </div>
              <% end %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Konrad cafe and bar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <!-- Detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

</head>
<body>


  <div class="wrapper">

    <%= render "shared/preloader" %>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= render "shared/js" %>



  </div><!-- .wrapper -->

</body>
</html>

app/views/layouts/cms.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Konradcafe CMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <!-- Detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

</head>
<body>

  <div class="wrapper">  <!-- Wrapper Start-->

  <!-- Navigation start     -->

   <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">KONRAD CMS</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">




        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">CMS Home</a></li>
          <li><a href="#">Cover Page Image</a></li>
          <li><%= link_to "Events", events_admin_path %></li>
          <li><%= link_to "Eat & Drink", eats_admin_path %></li>


          <!-- <li><a href="#">Contact</a></li> -->
        <!--   <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li> -->
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- Navigation End -->



  <%= yield %>



  <!-- Footer start -->

    <footer id="footer">

      <div class="container">

        <div class="row">

          <div class="col-md-12">
            <p class="copy">
              © 2015 Konrad Cafe & Bar, All Rights Reserved.
            </p>
          </div>

        </div><!-- .row -->

      </div><!-- .container -->

    </footer>

    <!-- Footer end -->

</div><!--  .Wrapper end -->


</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Konradcafe CMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <!-- Detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

</head>
<body>

  <div class="wrapper">  <!-- Wrapper Start-->

    <%= render "shared/cms_navbar" %>

    <%= render 'shared/flashes' %>







  <%= yield %>



  <!-- Footer start -->

    <footer id="footer">

      <div class="container">

        <div class="row">

          <div class="col-md-12">
            <p class="copy">
              ©  <%= Time.now.year %> Konrad Cafe & Bar, All Rights Reserved. Konrad CMS
            </p>
          </div>

        </div><!-- .row -->

      </div><!-- .container -->

    </footer>

    <!-- Footer end -->

</div><!--  .Wrapper end -->


</body>
</html>

app/views/shared/_cms_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "konrad_logo_red.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <%= "Signed in as: #{current_user.email}"  %>

      <!-- Text link -->
       <%= link_to "Home", admin_dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>

       <%= link_to "Cover (default)", covers_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "Events", events_admin_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "Eat & Drink", eats_index_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "Curries of the Week", edit_curry_path(1), class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "Opening Hours", opening_hours_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to "User Admin", admin_index_path, class: "navbar-wagon-item navbar-wagon-link" %>



      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>


  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer start -->

    <footer id="footer">

      <div class="container">

        <div class="row">

          <div class="col-md-12">
            <p class="copy">
              © <%= Date.today.strftime("%Y") %> Konrad Café & Bar, All Rights Reserved.
            </p>
          </div>

        </div><!-- .row -->

      </div><!-- .container -->

    </footer>

    <!-- Footer end -->

app/views/shared/_js.html.erb
<!-- AddEvent -->
<script type="text/javascript" src="https://addevent.com/libs/atc/1.6.1/atc.min.js"></script>

app/views/shared/_navbar.html.erb
 <!-- Navigation start -->

    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- Logo images below are shown and hidden on scroll  -->
          <!-- White Logo -->
          <div class="col-md-4 logo_white wow">
            <%= image_tag "konrad_logo.png", {class: "navlogo"}%>
         </div>
         <!-- Black logo -->
          <div class="col-md-3 logo_black wow">
           <%= image_tag "konrad_logo2.png", {class: "navlogo2"}%>
         </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">

            <li><a href="#coffee">Eat & Drink</a></li>
            <li><a href="#events">Events</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div>

      </div>
    </nav>

    <!-- Navigation end -->

app/views/shared/_old_navbar.html.erb
  <!-- Navigation start     -->

   <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">KONRAD CMS</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">




        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">CMS Home</a></li>
          <li><a href="#">Cover Page Image</a></li>
          <li><%= link_to "Events", events_admin_path %></li>
          <li><%= link_to "Eat & Drink", eats_admin_path %></li>


          <!-- <li><a href="#">Contact</a></li> -->
        <!--   <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li> -->
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <p>Hello: <%= current_user.email %></p>

  <!-- Navigation End -->

app/views/shared/_preloader.html.erb
<!-- Preloader -->

    <div id="preloader">
      <div id="status">
        <div class="status-mes"><h4>KONRAD Cafe & Bar</h4></div>
      </div>
    </div>